build: false
shallow_clone: true
platform:
  - x86
  - x64
clone_folder: c:\projects\json-reference

cache:
  - c:\tools\php -> appveyor.yml

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - set COMPOSER_PROCESS_TIMEOUT=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  - IF EXIST c:\tools\php (SET PHP=0)
  - IF %PHP%==1 cinst -y OpenSSL.Light
  - IF %PHP%==1 cinst -y php
  - cd c:\tools\php
  - IF %PHP%==1 copy php.ini-production php.ini /Y
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cd c:\projects\json-reference
  - composer install --prefer-dist --no-progress

before_test:
  - ps: $TestServer = Start-Process composer  -ArgumentList "test-server" -PassThru

test_script:
  - cd c:\projects\json-reference
  - vendor/bin/phpunit --colors=always

after_test:
  - ps: Stop-Process -Id $TestServer.Id
